### ISSUE TITLE
Can I translate your "Deep Learning for Beginners"?

### ISSUE THREAD

**Issue by weakish** [randomekek/randomekek.github.io#1]
Hi, I want to translate your ["Deep Learning for Beginners" note].
Can you give me the permission to translate & publish it?
(The translated text will be published at [ai.jqr.com],
and some related Chinese social network accounts.)
Thanks.

["Deep Learning for Beginners" note]: https://randomekek.github.io/deep/deeplearning.html
[ai.jqr.com]: https://ai.jqr.com

**Comment by randomekek** [comment]
Sure go ahead, this was just notes I wrote while reading the book.

**Comment by weakish** [comment]
Just finished the translation: https://www.jqr.com/article/000119
